ADPClientWebDemo/Controllers/callbackController.cs
using ADPClient;
using Microsoft.AspNetCore.Mvc;
using System;

namespace ADPClientWebDemo.Controllers
{
    public class callbackController : Controller
    {
        // GET: callback
        public ActionResult Index()
        {
            string returncode = null;
            AuthorizationCodeConnection connection = null;
            string error = Request.QueryString["error"];
            ViewBag.IsError = true;

            // checking if there were error/s from the api communication
            if (!String.IsNullOrEmpty(error))
            {
                ViewBag.Message = String.Format("Callback Error: {0}", error);
            }
            else {
                returncode = Request.QueryString["code"];

                // a successfull communication should result in an authorization code
                if (String.IsNullOrEmpty(returncode))
                {
                    ViewBag.Message = "Callback Error: Unauthorized";
                }
                else {
                    // callback was successfull so get connection from session
                    connection = HttpContext.Session["AuthorizationCodeConnection"] as AuthorizationCodeConnection;

                    if (connection == null)
                    {
                        ViewBag.Message = "Error: Session expired. Re-Authorization required.";
                    }
                    else {
                        // update connection's authorization code
                        ((AuthorizationCodeConfiguration)connection.connectionConfiguration).authorizationCode = returncode;
                        ViewBag.IsError = false;
                    }
                }

            }

            // cache connection in Session
            HttpContext.Session["AuthorizationCodeConnection"] = connection;

            return View("../marketplace/Index");
        }
    }
}

ADPClientWebDemo/Controllers/marketplaceController.cs
using System;
using ADPClient;
using Microsoft.AspNetCore.Mvc;

namespace ADPClientWebDemo
{
    public class marketplaceController : Controller
    {
        // GET: marketplace
        public ActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        public RedirectResult Authorize()
        {

            String authorizationurl = null;
            AuthorizationCodeConnection connection = null;

            // get new connection configuration
            // JSON config object placed in Web.config configuration or
            // set individual config object attributes
            String clientconfig = ADPClientWebDemo.Properties.Settings.Default.AuthorizationCodeConfiguration;

            if (String.IsNullOrEmpty(clientconfig))
            {
                ViewBag.IsError = true;
                ViewBag.Message = "Settings file or default options not available.";
            }
            else {
                // Initialize the Connection Configuration Object.
                // specifying the ConnectionConfiguration type will get back the right ConnectionConfiguration type object.
                // AuthorizationCodeConfiguration object is returned
                // JavaScriptSerializer oJS = new JavaScriptSerializer();
                AuthorizationCodeConfiguration connectionCfg = JSONUtil.Deserialize<AuthorizationCodeConfiguration>(clientconfig);

                // create a new connection based on the connection configuration object provided
                connection = (AuthorizationCodeConnection)ADPApiConnectionFactory.createConnection(connectionCfg);

                try
                {
                    // Authorization Code Apps require a user to login to ADP
                    // So obtain the authorization URL to redirect the user's
                    // browser so they can login
                    authorizationurl = connection.getAuthorizationURL();

                    // save connection for later use
                    HttpContext.Session["AuthorizationCodeConnection"] = connection;
                }
                catch (Exception e)
                {
                    ViewBag.isError = true;
                    ViewBag.Message = e.Message;
                }
            }

            return Redirect(authorizationurl);
        }

        public ActionResult getToken()
        {

            // get connection from session
            AuthorizationCodeConnection connection = HttpContext.Session["AuthorizationCodeConnection"] as AuthorizationCodeConnection;

            if (connection == null || ((AuthorizationCodeConfiguration)connection.connectionConfiguration).authorizationCode == null)
            {
                //is the connection available in session or is the 
                // cached connection expired then lets re-authorize
                return Authorize();
            }

            try
            {
                connection.connect();

                // connection was successfull 
                if (connection.isConnectedIndicator())
                {
                    // so get the worker like we wanted
                    ViewBag.Message = "Successfully connected to ADP API";
                }
            }
            catch (Exception e)
            {
                ViewBag.isError = true;
                ViewBag.Message = e.Message;
            }

            return View("Index");
        }

        public ActionResult getData()
        {
            // get connection from session
            AuthorizationCodeConnection connection = HttpContext.Session["AuthorizationCodeConnection"] as AuthorizationCodeConnection;

            if (connection == null || ((AuthorizationCodeConfiguration)connection.connectionConfiguration).authorizationCode == null)
            {
                //is the connection available in session or is the 
                // cached connection expired then lets re-authorize
                ViewBag.Message = "Not logged in or no connection available";
            }
            else {
                try
                {
                    connection.connect();

                    // connection was successfull 
                    if (connection.isConnectedIndicator())
                    {
                        // so get the worker like we wanted
                        ViewBag.Message = "Successfully connected to ADP API";

                        // get data using Product URL
                        var data = connection.getADPData("https://iat-api.adp.com/core/v1/userinfo");
                        ViewBag.Message = data;
                    }
                }
                catch (Exception e)
                {
                    ViewBag.isError = true;
                    ViewBag.Message = e.Message;
                }
            }
            return View("Index");
        }

        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        public ActionResult Logout()
        {
            ViewBag.Message = "You're logged out.";
            HttpContext.Session["AuthorizationCodeConnection"] = null;

            return View("Index");
        }
    }
}

ADPClientWebDemo/Views/marketplace/Index.cshtml
@using ADPClient;
@{
    ViewBag.Title = "Home Page";
    AuthorizationCodeConnection connection = (AuthorizationCodeConnection)Session["AuthorizationCodeConnection"];
    string authorizationcode = (connection == null) ? "" : ((AuthorizationCodeConfiguration)connection.connectionConfiguration).authorizationCode;
    ADPAccessToken token = ((connection == null) ? null : connection.accessToken);
    string disabledgettoken = ((connection == null) ? "disabled=disabled" : "");
    string disabledgetdata = ((token == null) ? "disabled=disabled" : "");
}



@if (connection == null)
{
    <h4><a href="/marketplace/Authorize">Login</a></h4>
}
else {
    <h4><a href="/marketplace/Logout">Logout</a></h4>
    <p>
        <h5>Authentication code: @authorizationcode </h5>

        @if (token != null)
        {
            <h5>Token:</h5>
            <h5>
<pre>
Connected to API end point
Token:  
         AccessToken: @token.AccessToken
         TokenType:   @token.TokenType
         ExpiresIn:   @token.ExpiresIn
         Scope:       @token.Scope
</pre>
            </h5>
        }
        else
        {
            using (Html.BeginForm("getToken", "marketplace", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                <button @disabledgettoken type="submit" class="btn btn-primary" style="display:inline-block;">Get Token</button>@:&nbsp;&nbsp;&nbsp;
            }
        }
    </p>
}


<!--
@using (Html.BeginForm("getData", "marketplace", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <button @disabledgetdata type="submit" class="btn btn-primary" style="display:inline-block;">Get Data</button>@:&nbsp;&nbsp;&nbsp;
}
-->

<table class="table table-bordered table-hover">
    <thead>
        <tr class="success">
            <th>&nbsp;</th>
        </tr>
    </thead>

    <tfoot>
        @if (ViewBag.IsError == true)
            {
            <tr>
                <td colspan="6">
                    <div class="alert alert-danger" role="alert">An error occurred while retrieving data from the server. Please try again.<p>@ViewBag.Message</p></div>
                </td>
            </tr>
        }
        else
        {
            <tr>
                <td colspan="6">
                    <div class="alert alert-info" role="alert"><p>@ViewBag.Message</p></div>
                </td>
            </tr>
        }
    </tfoot>

    <tbody></tbody>
</table>